// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ai.proto

package com.reis.game.prototypes;

public final class AiProto {
  private AiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AiDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AiData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string aiType = 1;</code>
     */
    java.lang.String getAiType();
    /**
     * <code>string aiType = 1;</code>
     */
    com.google.protobuf.ByteString
        getAiTypeBytes();

    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    java.util.List<com.reis.game.prototypes.AiProto.Waypoint> 
        getWaypointList();
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    com.reis.game.prototypes.AiProto.Waypoint getWaypoint(int index);
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    int getWaypointCount();
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    java.util.List<? extends com.reis.game.prototypes.AiProto.WaypointOrBuilder> 
        getWaypointOrBuilderList();
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    com.reis.game.prototypes.AiProto.WaypointOrBuilder getWaypointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AiData}
   */
  public  static final class AiData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AiData)
      AiDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AiData.newBuilder() to construct.
    private AiData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AiData() {
      aiType_ = "";
      waypoint_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AiData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              aiType_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                waypoint_ = new java.util.ArrayList<com.reis.game.prototypes.AiProto.Waypoint>();
                mutable_bitField0_ |= 0x00000002;
              }
              waypoint_.add(
                  input.readMessage(com.reis.game.prototypes.AiProto.Waypoint.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          waypoint_ = java.util.Collections.unmodifiableList(waypoint_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.prototypes.AiProto.internal_static_AiData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.prototypes.AiProto.internal_static_AiData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.prototypes.AiProto.AiData.class, com.reis.game.prototypes.AiProto.AiData.Builder.class);
    }

    private int bitField0_;
    public static final int AITYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object aiType_;
    /**
     * <code>string aiType = 1;</code>
     */
    public java.lang.String getAiType() {
      java.lang.Object ref = aiType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aiType_ = s;
        return s;
      }
    }
    /**
     * <code>string aiType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAiTypeBytes() {
      java.lang.Object ref = aiType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aiType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WAYPOINT_FIELD_NUMBER = 2;
    private java.util.List<com.reis.game.prototypes.AiProto.Waypoint> waypoint_;
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    public java.util.List<com.reis.game.prototypes.AiProto.Waypoint> getWaypointList() {
      return waypoint_;
    }
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    public java.util.List<? extends com.reis.game.prototypes.AiProto.WaypointOrBuilder> 
        getWaypointOrBuilderList() {
      return waypoint_;
    }
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    public int getWaypointCount() {
      return waypoint_.size();
    }
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    public com.reis.game.prototypes.AiProto.Waypoint getWaypoint(int index) {
      return waypoint_.get(index);
    }
    /**
     * <code>repeated .Waypoint waypoint = 2;</code>
     */
    public com.reis.game.prototypes.AiProto.WaypointOrBuilder getWaypointOrBuilder(
        int index) {
      return waypoint_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAiTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aiType_);
      }
      for (int i = 0; i < waypoint_.size(); i++) {
        output.writeMessage(2, waypoint_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAiTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aiType_);
      }
      for (int i = 0; i < waypoint_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, waypoint_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.prototypes.AiProto.AiData)) {
        return super.equals(obj);
      }
      com.reis.game.prototypes.AiProto.AiData other = (com.reis.game.prototypes.AiProto.AiData) obj;

      boolean result = true;
      result = result && getAiType()
          .equals(other.getAiType());
      result = result && getWaypointList()
          .equals(other.getWaypointList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AITYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAiType().hashCode();
      if (getWaypointCount() > 0) {
        hash = (37 * hash) + WAYPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getWaypointList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.AiData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.prototypes.AiProto.AiData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AiData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AiData)
        com.reis.game.prototypes.AiProto.AiDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.prototypes.AiProto.internal_static_AiData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.prototypes.AiProto.internal_static_AiData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.prototypes.AiProto.AiData.class, com.reis.game.prototypes.AiProto.AiData.Builder.class);
      }

      // Construct using com.reis.game.prototypes.AiProto.AiData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWaypointFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        aiType_ = "";

        if (waypointBuilder_ == null) {
          waypoint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          waypointBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.prototypes.AiProto.internal_static_AiData_descriptor;
      }

      public com.reis.game.prototypes.AiProto.AiData getDefaultInstanceForType() {
        return com.reis.game.prototypes.AiProto.AiData.getDefaultInstance();
      }

      public com.reis.game.prototypes.AiProto.AiData build() {
        com.reis.game.prototypes.AiProto.AiData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.prototypes.AiProto.AiData buildPartial() {
        com.reis.game.prototypes.AiProto.AiData result = new com.reis.game.prototypes.AiProto.AiData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.aiType_ = aiType_;
        if (waypointBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            waypoint_ = java.util.Collections.unmodifiableList(waypoint_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.waypoint_ = waypoint_;
        } else {
          result.waypoint_ = waypointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.prototypes.AiProto.AiData) {
          return mergeFrom((com.reis.game.prototypes.AiProto.AiData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.prototypes.AiProto.AiData other) {
        if (other == com.reis.game.prototypes.AiProto.AiData.getDefaultInstance()) return this;
        if (!other.getAiType().isEmpty()) {
          aiType_ = other.aiType_;
          onChanged();
        }
        if (waypointBuilder_ == null) {
          if (!other.waypoint_.isEmpty()) {
            if (waypoint_.isEmpty()) {
              waypoint_ = other.waypoint_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureWaypointIsMutable();
              waypoint_.addAll(other.waypoint_);
            }
            onChanged();
          }
        } else {
          if (!other.waypoint_.isEmpty()) {
            if (waypointBuilder_.isEmpty()) {
              waypointBuilder_.dispose();
              waypointBuilder_ = null;
              waypoint_ = other.waypoint_;
              bitField0_ = (bitField0_ & ~0x00000002);
              waypointBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWaypointFieldBuilder() : null;
            } else {
              waypointBuilder_.addAllMessages(other.waypoint_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.prototypes.AiProto.AiData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.prototypes.AiProto.AiData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object aiType_ = "";
      /**
       * <code>string aiType = 1;</code>
       */
      public java.lang.String getAiType() {
        java.lang.Object ref = aiType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          aiType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string aiType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAiTypeBytes() {
        java.lang.Object ref = aiType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aiType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string aiType = 1;</code>
       */
      public Builder setAiType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        aiType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string aiType = 1;</code>
       */
      public Builder clearAiType() {
        
        aiType_ = getDefaultInstance().getAiType();
        onChanged();
        return this;
      }
      /**
       * <code>string aiType = 1;</code>
       */
      public Builder setAiTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        aiType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.reis.game.prototypes.AiProto.Waypoint> waypoint_ =
        java.util.Collections.emptyList();
      private void ensureWaypointIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          waypoint_ = new java.util.ArrayList<com.reis.game.prototypes.AiProto.Waypoint>(waypoint_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.prototypes.AiProto.Waypoint, com.reis.game.prototypes.AiProto.Waypoint.Builder, com.reis.game.prototypes.AiProto.WaypointOrBuilder> waypointBuilder_;

      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public java.util.List<com.reis.game.prototypes.AiProto.Waypoint> getWaypointList() {
        if (waypointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(waypoint_);
        } else {
          return waypointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public int getWaypointCount() {
        if (waypointBuilder_ == null) {
          return waypoint_.size();
        } else {
          return waypointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public com.reis.game.prototypes.AiProto.Waypoint getWaypoint(int index) {
        if (waypointBuilder_ == null) {
          return waypoint_.get(index);
        } else {
          return waypointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder setWaypoint(
          int index, com.reis.game.prototypes.AiProto.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.set(index, value);
          onChanged();
        } else {
          waypointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder setWaypoint(
          int index, com.reis.game.prototypes.AiProto.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.set(index, builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder addWaypoint(com.reis.game.prototypes.AiProto.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.add(value);
          onChanged();
        } else {
          waypointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder addWaypoint(
          int index, com.reis.game.prototypes.AiProto.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.add(index, value);
          onChanged();
        } else {
          waypointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder addWaypoint(
          com.reis.game.prototypes.AiProto.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.add(builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder addWaypoint(
          int index, com.reis.game.prototypes.AiProto.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.add(index, builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder addAllWaypoint(
          java.lang.Iterable<? extends com.reis.game.prototypes.AiProto.Waypoint> values) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, waypoint_);
          onChanged();
        } else {
          waypointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder clearWaypoint() {
        if (waypointBuilder_ == null) {
          waypoint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          waypointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public Builder removeWaypoint(int index) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.remove(index);
          onChanged();
        } else {
          waypointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public com.reis.game.prototypes.AiProto.Waypoint.Builder getWaypointBuilder(
          int index) {
        return getWaypointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public com.reis.game.prototypes.AiProto.WaypointOrBuilder getWaypointOrBuilder(
          int index) {
        if (waypointBuilder_ == null) {
          return waypoint_.get(index);  } else {
          return waypointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public java.util.List<? extends com.reis.game.prototypes.AiProto.WaypointOrBuilder> 
           getWaypointOrBuilderList() {
        if (waypointBuilder_ != null) {
          return waypointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(waypoint_);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public com.reis.game.prototypes.AiProto.Waypoint.Builder addWaypointBuilder() {
        return getWaypointFieldBuilder().addBuilder(
            com.reis.game.prototypes.AiProto.Waypoint.getDefaultInstance());
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public com.reis.game.prototypes.AiProto.Waypoint.Builder addWaypointBuilder(
          int index) {
        return getWaypointFieldBuilder().addBuilder(
            index, com.reis.game.prototypes.AiProto.Waypoint.getDefaultInstance());
      }
      /**
       * <code>repeated .Waypoint waypoint = 2;</code>
       */
      public java.util.List<com.reis.game.prototypes.AiProto.Waypoint.Builder> 
           getWaypointBuilderList() {
        return getWaypointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.prototypes.AiProto.Waypoint, com.reis.game.prototypes.AiProto.Waypoint.Builder, com.reis.game.prototypes.AiProto.WaypointOrBuilder> 
          getWaypointFieldBuilder() {
        if (waypointBuilder_ == null) {
          waypointBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.prototypes.AiProto.Waypoint, com.reis.game.prototypes.AiProto.Waypoint.Builder, com.reis.game.prototypes.AiProto.WaypointOrBuilder>(
                  waypoint_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          waypoint_ = null;
        }
        return waypointBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AiData)
    }

    // @@protoc_insertion_point(class_scope:AiData)
    private static final com.reis.game.prototypes.AiProto.AiData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.prototypes.AiProto.AiData();
    }

    public static com.reis.game.prototypes.AiProto.AiData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AiData>
        PARSER = new com.google.protobuf.AbstractParser<AiData>() {
      public AiData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AiData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AiData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AiData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.prototypes.AiProto.AiData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WaypointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Waypoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 row = 1;</code>
     */
    int getRow();

    /**
     * <code>int32 col = 2;</code>
     */
    int getCol();
  }
  /**
   * Protobuf type {@code Waypoint}
   */
  public  static final class Waypoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Waypoint)
      WaypointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Waypoint.newBuilder() to construct.
    private Waypoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Waypoint() {
      row_ = 0;
      col_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Waypoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              row_ = input.readInt32();
              break;
            }
            case 16: {

              col_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.prototypes.AiProto.internal_static_Waypoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.prototypes.AiProto.internal_static_Waypoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.prototypes.AiProto.Waypoint.class, com.reis.game.prototypes.AiProto.Waypoint.Builder.class);
    }

    public static final int ROW_FIELD_NUMBER = 1;
    private int row_;
    /**
     * <code>int32 row = 1;</code>
     */
    public int getRow() {
      return row_;
    }

    public static final int COL_FIELD_NUMBER = 2;
    private int col_;
    /**
     * <code>int32 col = 2;</code>
     */
    public int getCol() {
      return col_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (row_ != 0) {
        output.writeInt32(1, row_);
      }
      if (col_ != 0) {
        output.writeInt32(2, col_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (row_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, row_);
      }
      if (col_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, col_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.prototypes.AiProto.Waypoint)) {
        return super.equals(obj);
      }
      com.reis.game.prototypes.AiProto.Waypoint other = (com.reis.game.prototypes.AiProto.Waypoint) obj;

      boolean result = true;
      result = result && (getRow()
          == other.getRow());
      result = result && (getCol()
          == other.getCol());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + getRow();
      hash = (37 * hash) + COL_FIELD_NUMBER;
      hash = (53 * hash) + getCol();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.AiProto.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.prototypes.AiProto.Waypoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Waypoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Waypoint)
        com.reis.game.prototypes.AiProto.WaypointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.prototypes.AiProto.internal_static_Waypoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.prototypes.AiProto.internal_static_Waypoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.prototypes.AiProto.Waypoint.class, com.reis.game.prototypes.AiProto.Waypoint.Builder.class);
      }

      // Construct using com.reis.game.prototypes.AiProto.Waypoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        row_ = 0;

        col_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.prototypes.AiProto.internal_static_Waypoint_descriptor;
      }

      public com.reis.game.prototypes.AiProto.Waypoint getDefaultInstanceForType() {
        return com.reis.game.prototypes.AiProto.Waypoint.getDefaultInstance();
      }

      public com.reis.game.prototypes.AiProto.Waypoint build() {
        com.reis.game.prototypes.AiProto.Waypoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.prototypes.AiProto.Waypoint buildPartial() {
        com.reis.game.prototypes.AiProto.Waypoint result = new com.reis.game.prototypes.AiProto.Waypoint(this);
        result.row_ = row_;
        result.col_ = col_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.prototypes.AiProto.Waypoint) {
          return mergeFrom((com.reis.game.prototypes.AiProto.Waypoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.prototypes.AiProto.Waypoint other) {
        if (other == com.reis.game.prototypes.AiProto.Waypoint.getDefaultInstance()) return this;
        if (other.getRow() != 0) {
          setRow(other.getRow());
        }
        if (other.getCol() != 0) {
          setCol(other.getCol());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.prototypes.AiProto.Waypoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.prototypes.AiProto.Waypoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int row_ ;
      /**
       * <code>int32 row = 1;</code>
       */
      public int getRow() {
        return row_;
      }
      /**
       * <code>int32 row = 1;</code>
       */
      public Builder setRow(int value) {
        
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 row = 1;</code>
       */
      public Builder clearRow() {
        
        row_ = 0;
        onChanged();
        return this;
      }

      private int col_ ;
      /**
       * <code>int32 col = 2;</code>
       */
      public int getCol() {
        return col_;
      }
      /**
       * <code>int32 col = 2;</code>
       */
      public Builder setCol(int value) {
        
        col_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 col = 2;</code>
       */
      public Builder clearCol() {
        
        col_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Waypoint)
    }

    // @@protoc_insertion_point(class_scope:Waypoint)
    private static final com.reis.game.prototypes.AiProto.Waypoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.prototypes.AiProto.Waypoint();
    }

    public static com.reis.game.prototypes.AiProto.Waypoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Waypoint>
        PARSER = new com.google.protobuf.AbstractParser<Waypoint>() {
      public Waypoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Waypoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Waypoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Waypoint> getParserForType() {
      return PARSER;
    }

    public com.reis.game.prototypes.AiProto.Waypoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AiData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AiData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Waypoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Waypoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010ai.proto\"5\n\006AiData\022\016\n\006aiType\030\001 \001(\t\022\033\n\010" +
      "waypoint\030\002 \003(\0132\t.Waypoint\"$\n\010Waypoint\022\013\n" +
      "\003row\030\001 \001(\005\022\013\n\003col\030\002 \001(\005B#\n\030com.reis.game" +
      ".prototypesB\007AiProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AiData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AiData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AiData_descriptor,
        new java.lang.String[] { "AiType", "Waypoint", });
    internal_static_Waypoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Waypoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Waypoint_descriptor,
        new java.lang.String[] { "Row", "Col", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
