// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package com.reis.game.prototypes;

public final class EntityTypeProto {
  private EntityTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntityDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 row = 2;</code>
     */
    int getRow();

    /**
     * <code>int32 col = 3;</code>
     */
    int getCol();

    /**
     * <code>int32 width = 4;</code>
     */
    int getWidth();

    /**
     * <code>int32 height = 5;</code>
     */
    int getHeight();

    /**
     * <code>string templateName = 6;</code>
     */
    java.lang.String getTemplateName();
    /**
     * <code>string templateName = 6;</code>
     */
    com.google.protobuf.ByteString
        getTemplateNameBytes();

    /**
     * <code>.AiData aiData = 7;</code>
     */
    boolean hasAiData();
    /**
     * <code>.AiData aiData = 7;</code>
     */
    com.reis.game.prototypes.AiProto.AiData getAiData();
    /**
     * <code>.AiData aiData = 7;</code>
     */
    com.reis.game.prototypes.AiProto.AiDataOrBuilder getAiDataOrBuilder();

    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    boolean hasAnimationData();
    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    com.reis.game.prototypes.AnimationProto.AnimationData getAnimationData();
    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder getAnimationDataOrBuilder();
  }
  /**
   * Protobuf type {@code EntityData}
   */
  public  static final class EntityData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityData)
      EntityDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityData.newBuilder() to construct.
    private EntityData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityData() {
      id_ = 0;
      row_ = 0;
      col_ = 0;
      width_ = 0;
      height_ = 0;
      templateName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              row_ = input.readInt32();
              break;
            }
            case 24: {

              col_ = input.readInt32();
              break;
            }
            case 32: {

              width_ = input.readInt32();
              break;
            }
            case 40: {

              height_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              templateName_ = s;
              break;
            }
            case 58: {
              com.reis.game.prototypes.AiProto.AiData.Builder subBuilder = null;
              if (aiData_ != null) {
                subBuilder = aiData_.toBuilder();
              }
              aiData_ = input.readMessage(com.reis.game.prototypes.AiProto.AiData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(aiData_);
                aiData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              com.reis.game.prototypes.AnimationProto.AnimationData.Builder subBuilder = null;
              if (animationData_ != null) {
                subBuilder = animationData_.toBuilder();
              }
              animationData_ = input.readMessage(com.reis.game.prototypes.AnimationProto.AnimationData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(animationData_);
                animationData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.prototypes.EntityTypeProto.internal_static_EntityData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.prototypes.EntityTypeProto.internal_static_EntityData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.prototypes.EntityTypeProto.EntityData.class, com.reis.game.prototypes.EntityTypeProto.EntityData.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ROW_FIELD_NUMBER = 2;
    private int row_;
    /**
     * <code>int32 row = 2;</code>
     */
    public int getRow() {
      return row_;
    }

    public static final int COL_FIELD_NUMBER = 3;
    private int col_;
    /**
     * <code>int32 col = 3;</code>
     */
    public int getCol() {
      return col_;
    }

    public static final int WIDTH_FIELD_NUMBER = 4;
    private int width_;
    /**
     * <code>int32 width = 4;</code>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 5;
    private int height_;
    /**
     * <code>int32 height = 5;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int TEMPLATENAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object templateName_;
    /**
     * <code>string templateName = 6;</code>
     */
    public java.lang.String getTemplateName() {
      java.lang.Object ref = templateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateName_ = s;
        return s;
      }
    }
    /**
     * <code>string templateName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateNameBytes() {
      java.lang.Object ref = templateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AIDATA_FIELD_NUMBER = 7;
    private com.reis.game.prototypes.AiProto.AiData aiData_;
    /**
     * <code>.AiData aiData = 7;</code>
     */
    public boolean hasAiData() {
      return aiData_ != null;
    }
    /**
     * <code>.AiData aiData = 7;</code>
     */
    public com.reis.game.prototypes.AiProto.AiData getAiData() {
      return aiData_ == null ? com.reis.game.prototypes.AiProto.AiData.getDefaultInstance() : aiData_;
    }
    /**
     * <code>.AiData aiData = 7;</code>
     */
    public com.reis.game.prototypes.AiProto.AiDataOrBuilder getAiDataOrBuilder() {
      return getAiData();
    }

    public static final int ANIMATIONDATA_FIELD_NUMBER = 8;
    private com.reis.game.prototypes.AnimationProto.AnimationData animationData_;
    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    public boolean hasAnimationData() {
      return animationData_ != null;
    }
    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    public com.reis.game.prototypes.AnimationProto.AnimationData getAnimationData() {
      return animationData_ == null ? com.reis.game.prototypes.AnimationProto.AnimationData.getDefaultInstance() : animationData_;
    }
    /**
     * <code>.AnimationData animationData = 8;</code>
     */
    public com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder getAnimationDataOrBuilder() {
      return getAnimationData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (row_ != 0) {
        output.writeInt32(2, row_);
      }
      if (col_ != 0) {
        output.writeInt32(3, col_);
      }
      if (width_ != 0) {
        output.writeInt32(4, width_);
      }
      if (height_ != 0) {
        output.writeInt32(5, height_);
      }
      if (!getTemplateNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, templateName_);
      }
      if (aiData_ != null) {
        output.writeMessage(7, getAiData());
      }
      if (animationData_ != null) {
        output.writeMessage(8, getAnimationData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (row_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, row_);
      }
      if (col_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, col_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, height_);
      }
      if (!getTemplateNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, templateName_);
      }
      if (aiData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getAiData());
      }
      if (animationData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getAnimationData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.prototypes.EntityTypeProto.EntityData)) {
        return super.equals(obj);
      }
      com.reis.game.prototypes.EntityTypeProto.EntityData other = (com.reis.game.prototypes.EntityTypeProto.EntityData) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getRow()
          == other.getRow());
      result = result && (getCol()
          == other.getCol());
      result = result && (getWidth()
          == other.getWidth());
      result = result && (getHeight()
          == other.getHeight());
      result = result && getTemplateName()
          .equals(other.getTemplateName());
      result = result && (hasAiData() == other.hasAiData());
      if (hasAiData()) {
        result = result && getAiData()
            .equals(other.getAiData());
      }
      result = result && (hasAnimationData() == other.hasAnimationData());
      if (hasAnimationData()) {
        result = result && getAnimationData()
            .equals(other.getAnimationData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + getRow();
      hash = (37 * hash) + COL_FIELD_NUMBER;
      hash = (53 * hash) + getCol();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + TEMPLATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateName().hashCode();
      if (hasAiData()) {
        hash = (37 * hash) + AIDATA_FIELD_NUMBER;
        hash = (53 * hash) + getAiData().hashCode();
      }
      if (hasAnimationData()) {
        hash = (37 * hash) + ANIMATIONDATA_FIELD_NUMBER;
        hash = (53 * hash) + getAnimationData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.prototypes.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.prototypes.EntityTypeProto.EntityData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EntityData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityData)
        com.reis.game.prototypes.EntityTypeProto.EntityDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.prototypes.EntityTypeProto.internal_static_EntityData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.prototypes.EntityTypeProto.internal_static_EntityData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.prototypes.EntityTypeProto.EntityData.class, com.reis.game.prototypes.EntityTypeProto.EntityData.Builder.class);
      }

      // Construct using com.reis.game.prototypes.EntityTypeProto.EntityData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        row_ = 0;

        col_ = 0;

        width_ = 0;

        height_ = 0;

        templateName_ = "";

        if (aiDataBuilder_ == null) {
          aiData_ = null;
        } else {
          aiData_ = null;
          aiDataBuilder_ = null;
        }
        if (animationDataBuilder_ == null) {
          animationData_ = null;
        } else {
          animationData_ = null;
          animationDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.prototypes.EntityTypeProto.internal_static_EntityData_descriptor;
      }

      public com.reis.game.prototypes.EntityTypeProto.EntityData getDefaultInstanceForType() {
        return com.reis.game.prototypes.EntityTypeProto.EntityData.getDefaultInstance();
      }

      public com.reis.game.prototypes.EntityTypeProto.EntityData build() {
        com.reis.game.prototypes.EntityTypeProto.EntityData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.prototypes.EntityTypeProto.EntityData buildPartial() {
        com.reis.game.prototypes.EntityTypeProto.EntityData result = new com.reis.game.prototypes.EntityTypeProto.EntityData(this);
        result.id_ = id_;
        result.row_ = row_;
        result.col_ = col_;
        result.width_ = width_;
        result.height_ = height_;
        result.templateName_ = templateName_;
        if (aiDataBuilder_ == null) {
          result.aiData_ = aiData_;
        } else {
          result.aiData_ = aiDataBuilder_.build();
        }
        if (animationDataBuilder_ == null) {
          result.animationData_ = animationData_;
        } else {
          result.animationData_ = animationDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.prototypes.EntityTypeProto.EntityData) {
          return mergeFrom((com.reis.game.prototypes.EntityTypeProto.EntityData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.prototypes.EntityTypeProto.EntityData other) {
        if (other == com.reis.game.prototypes.EntityTypeProto.EntityData.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getRow() != 0) {
          setRow(other.getRow());
        }
        if (other.getCol() != 0) {
          setCol(other.getCol());
        }
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (!other.getTemplateName().isEmpty()) {
          templateName_ = other.templateName_;
          onChanged();
        }
        if (other.hasAiData()) {
          mergeAiData(other.getAiData());
        }
        if (other.hasAnimationData()) {
          mergeAnimationData(other.getAnimationData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.prototypes.EntityTypeProto.EntityData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.prototypes.EntityTypeProto.EntityData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int row_ ;
      /**
       * <code>int32 row = 2;</code>
       */
      public int getRow() {
        return row_;
      }
      /**
       * <code>int32 row = 2;</code>
       */
      public Builder setRow(int value) {
        
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 row = 2;</code>
       */
      public Builder clearRow() {
        
        row_ = 0;
        onChanged();
        return this;
      }

      private int col_ ;
      /**
       * <code>int32 col = 3;</code>
       */
      public int getCol() {
        return col_;
      }
      /**
       * <code>int32 col = 3;</code>
       */
      public Builder setCol(int value) {
        
        col_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 col = 3;</code>
       */
      public Builder clearCol() {
        
        col_ = 0;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 4;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 4;</code>
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 4;</code>
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 5;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 5;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 5;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object templateName_ = "";
      /**
       * <code>string templateName = 6;</code>
       */
      public java.lang.String getTemplateName() {
        java.lang.Object ref = templateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          templateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string templateName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateNameBytes() {
        java.lang.Object ref = templateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string templateName = 6;</code>
       */
      public Builder setTemplateName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string templateName = 6;</code>
       */
      public Builder clearTemplateName() {
        
        templateName_ = getDefaultInstance().getTemplateName();
        onChanged();
        return this;
      }
      /**
       * <code>string templateName = 6;</code>
       */
      public Builder setTemplateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateName_ = value;
        onChanged();
        return this;
      }

      private com.reis.game.prototypes.AiProto.AiData aiData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.prototypes.AiProto.AiData, com.reis.game.prototypes.AiProto.AiData.Builder, com.reis.game.prototypes.AiProto.AiDataOrBuilder> aiDataBuilder_;
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public boolean hasAiData() {
        return aiDataBuilder_ != null || aiData_ != null;
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public com.reis.game.prototypes.AiProto.AiData getAiData() {
        if (aiDataBuilder_ == null) {
          return aiData_ == null ? com.reis.game.prototypes.AiProto.AiData.getDefaultInstance() : aiData_;
        } else {
          return aiDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public Builder setAiData(com.reis.game.prototypes.AiProto.AiData value) {
        if (aiDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          aiData_ = value;
          onChanged();
        } else {
          aiDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public Builder setAiData(
          com.reis.game.prototypes.AiProto.AiData.Builder builderForValue) {
        if (aiDataBuilder_ == null) {
          aiData_ = builderForValue.build();
          onChanged();
        } else {
          aiDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public Builder mergeAiData(com.reis.game.prototypes.AiProto.AiData value) {
        if (aiDataBuilder_ == null) {
          if (aiData_ != null) {
            aiData_ =
              com.reis.game.prototypes.AiProto.AiData.newBuilder(aiData_).mergeFrom(value).buildPartial();
          } else {
            aiData_ = value;
          }
          onChanged();
        } else {
          aiDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public Builder clearAiData() {
        if (aiDataBuilder_ == null) {
          aiData_ = null;
          onChanged();
        } else {
          aiData_ = null;
          aiDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public com.reis.game.prototypes.AiProto.AiData.Builder getAiDataBuilder() {
        
        onChanged();
        return getAiDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      public com.reis.game.prototypes.AiProto.AiDataOrBuilder getAiDataOrBuilder() {
        if (aiDataBuilder_ != null) {
          return aiDataBuilder_.getMessageOrBuilder();
        } else {
          return aiData_ == null ?
              com.reis.game.prototypes.AiProto.AiData.getDefaultInstance() : aiData_;
        }
      }
      /**
       * <code>.AiData aiData = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.prototypes.AiProto.AiData, com.reis.game.prototypes.AiProto.AiData.Builder, com.reis.game.prototypes.AiProto.AiDataOrBuilder> 
          getAiDataFieldBuilder() {
        if (aiDataBuilder_ == null) {
          aiDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.reis.game.prototypes.AiProto.AiData, com.reis.game.prototypes.AiProto.AiData.Builder, com.reis.game.prototypes.AiProto.AiDataOrBuilder>(
                  getAiData(),
                  getParentForChildren(),
                  isClean());
          aiData_ = null;
        }
        return aiDataBuilder_;
      }

      private com.reis.game.prototypes.AnimationProto.AnimationData animationData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.prototypes.AnimationProto.AnimationData, com.reis.game.prototypes.AnimationProto.AnimationData.Builder, com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder> animationDataBuilder_;
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public boolean hasAnimationData() {
        return animationDataBuilder_ != null || animationData_ != null;
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public com.reis.game.prototypes.AnimationProto.AnimationData getAnimationData() {
        if (animationDataBuilder_ == null) {
          return animationData_ == null ? com.reis.game.prototypes.AnimationProto.AnimationData.getDefaultInstance() : animationData_;
        } else {
          return animationDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public Builder setAnimationData(com.reis.game.prototypes.AnimationProto.AnimationData value) {
        if (animationDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          animationData_ = value;
          onChanged();
        } else {
          animationDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public Builder setAnimationData(
          com.reis.game.prototypes.AnimationProto.AnimationData.Builder builderForValue) {
        if (animationDataBuilder_ == null) {
          animationData_ = builderForValue.build();
          onChanged();
        } else {
          animationDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public Builder mergeAnimationData(com.reis.game.prototypes.AnimationProto.AnimationData value) {
        if (animationDataBuilder_ == null) {
          if (animationData_ != null) {
            animationData_ =
              com.reis.game.prototypes.AnimationProto.AnimationData.newBuilder(animationData_).mergeFrom(value).buildPartial();
          } else {
            animationData_ = value;
          }
          onChanged();
        } else {
          animationDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public Builder clearAnimationData() {
        if (animationDataBuilder_ == null) {
          animationData_ = null;
          onChanged();
        } else {
          animationData_ = null;
          animationDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public com.reis.game.prototypes.AnimationProto.AnimationData.Builder getAnimationDataBuilder() {
        
        onChanged();
        return getAnimationDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      public com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder getAnimationDataOrBuilder() {
        if (animationDataBuilder_ != null) {
          return animationDataBuilder_.getMessageOrBuilder();
        } else {
          return animationData_ == null ?
              com.reis.game.prototypes.AnimationProto.AnimationData.getDefaultInstance() : animationData_;
        }
      }
      /**
       * <code>.AnimationData animationData = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.prototypes.AnimationProto.AnimationData, com.reis.game.prototypes.AnimationProto.AnimationData.Builder, com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder> 
          getAnimationDataFieldBuilder() {
        if (animationDataBuilder_ == null) {
          animationDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.reis.game.prototypes.AnimationProto.AnimationData, com.reis.game.prototypes.AnimationProto.AnimationData.Builder, com.reis.game.prototypes.AnimationProto.AnimationDataOrBuilder>(
                  getAnimationData(),
                  getParentForChildren(),
                  isClean());
          animationData_ = null;
        }
        return animationDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityData)
    }

    // @@protoc_insertion_point(class_scope:EntityData)
    private static final com.reis.game.prototypes.EntityTypeProto.EntityData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.prototypes.EntityTypeProto.EntityData();
    }

    public static com.reis.game.prototypes.EntityTypeProto.EntityData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityData>
        PARSER = new com.google.protobuf.AbstractParser<EntityData>() {
      public EntityData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntityData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.prototypes.EntityTypeProto.EntityData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014entity.proto\032\010ai.proto\032\017animation.prot" +
      "o\"\247\001\n\nEntityData\022\n\n\002id\030\001 \001(\005\022\013\n\003row\030\002 \001(" +
      "\005\022\013\n\003col\030\003 \001(\005\022\r\n\005width\030\004 \001(\005\022\016\n\006height\030" +
      "\005 \001(\005\022\024\n\014templateName\030\006 \001(\t\022\027\n\006aiData\030\007 " +
      "\001(\0132\007.AiData\022%\n\ranimationData\030\010 \001(\0132\016.An" +
      "imationDataB+\n\030com.reis.game.prototypesB" +
      "\017EntityTypeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.reis.game.prototypes.AiProto.getDescriptor(),
          com.reis.game.prototypes.AnimationProto.getDescriptor(),
        }, assigner);
    internal_static_EntityData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EntityData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityData_descriptor,
        new java.lang.String[] { "Id", "Row", "Col", "Width", "Height", "TemplateName", "AiData", "AnimationData", });
    com.reis.game.prototypes.AiProto.getDescriptor();
    com.reis.game.prototypes.AnimationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
